//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kanban.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class board
    {
        public int id { get; set; }
        public string title { get; set; }
        public int account_id { get; set; }
    
        public virtual account account { get; set; }
    }
}
